### ISSUE TITLE
when editing an existing todo, the old values are not displayed

### ISSUE THREAD

**Issue by 8dzed2** [8dzed2/SS18-PJSN2#3]
don't use the django form in the html file, but rather look into implementing it in python

**Comment by Pazifistin** [comment]
for me it works just fine, ok that's not quite correct. If i change one of the created ToDos and hit submit, the untreated ToDo still appears next to the edited ToDo, so i'm therefore forced to delete the unedited ToDo.

... will work on it tomorrow

**Comment by Pazifistin** [comment]
oh , you surely meant the change-process : that someone always has to re-enter everything during this process, even though someone only wants to change the "progress" not the "description"...
